module.exports = {
    q1: [
        'Apa judul film yang dibintangi oleh {actor}?',
        'Apa saja judul film yang dibintangi oleh {actor}?',
        'Apa nama film yang dibintangi oleh {actor}?',
        'Apa saja nama film yang dibintangi oleh {actor}?',
        'Film apa yang dibintangi oleh {actor}?',
        'Film apa saja yang dibintangi oleh {actor}?',
        'Apa judul film yang dibintangi {actor}?',
        'Apa saja judul film yang dibintangi {actor}?',
        'Apa nama film yang dibintangi {actor}?',
        'Apa saja nama film yang dibintangi {actor}?',
        'Film apa yang dibintangi {actor}?',
        'Film apa saja yang dibintangi {actor}?',
        'Aktor {actor} membintangi film apa?',
        'Aktor {actor} membintangi film apa saja?',
        'Apa judul film yang diperankan oleh {actor}?',
        'Apa saja judul film yang diperankan oleh {actor}?',
        'Apa nama film yang diperankan oleh {actor}?',
        'Apa saja nama film yang diperankan oleh {actor}?',
        'Film apa yang diperankan oleh {actor}?',
        'Film apa saja yang diperankan oleh {actor}?',
        'Apa judul film yang diperankan {actor}?',
        'Apa saja judul film yang diperankan {actor}?',
        'Apa nama film yang diperankan {actor}?',
        'Apa saja nama film yang diperankan {actor}?',
        'Film apa yang diperankan {actor}?',
        'Film apa saja yang diperankan {actor}?',
        'Aktor {actor} memerankan film apa?',
        'Aktor {actor} memerankan film apa saja?',
        'Apa judul film yang dimainkan oleh {actor}?',
        'Apa saja judul film yang dimainkan oleh {actor}?',
        'Apa nama film yang dimainkan oleh {actor}?',
        'Apa saja nama film yang dimainkan oleh {actor}?',
        'Film apa yang dimainkan oleh {actor}?',
        'Film apa saja yang dimainkan oleh {actor}?',
        'Apa judul film yang dimainkan {actor}?',
        'Apa saja judul film yang dimainkan {actor}?',
        'Apa nama film yang dimainkan {actor}?',
        'Apa saja nama film yang dimainkan {actor}?',
        'Film apa yang dimainkan {actor}?',
        'Film apa saja yang dimainkan {actor}?',
        'Aktor {actor} memainkan film apa?',
        'Aktor {actor} memainkan film apa saja?'
    ],
    q2: [
        'Siapa saja aktor yang membintangi film {film}?',
        'Siapa saja yang membintangi film {film}?',
        'Siapa yang membintangi film {film}?',
        'Siapa aktor yang membintangi film {film}?',
        'Siapa saja aktor yang memerankan film {film}?',
        'Siapa saja yang memerankan film {film}?',
        'Siapa yang memerankan film {film}?',
        'Siapa aktor yang memerankan film {film}?',
        'Siapa saja aktor yang memainkan film {film}?',
        'Siapa saja yang memainkan film {film}?',
        'Siapa yang memainkan film {film}?',
        'Siapa aktor yang memainkan film {film}?'
    ],
    q3: [
        'Film {film} layak ditonton oleh siapa?',
        'Film {film} layak ditonton oleh siapa saja?',
        'Film {film} cocok ditonton oleh siapa?',
        'Film {film} cocok ditonton oleh siapa saja?',
        'Film {film} dapat ditonton oleh siapa?',
        'Film {film} dapat ditonton oleh siapa saja?',
        'Film {film} boleh ditonton oleh siapa?',
        'Film {film} boleh ditonton oleh siapa saja?',
        'Apa kategori dari film {film}?',
        'Apa kategori film {film}?'
    ],
    q4: [
        'Berapa durasi dari film {film}?',
        'Berapa durasi film {film}?',
        'Berapa lama durasi dari film {film}?',
        'Berapa lama durasi film {film}?',
        'Berapa lama film {film} diputar?'
    ],
    q5: [
        'Apa genre dari film {film}?',
        'Apa genre film {film}?',
        'Apa jenis genre dari film {film}?',
        'Apa jenis genre film {film}?',
        'Film {film} termasuk dalam genre apa?'
    ],
    q6: [
        'Apa sinopsis dari film {film}?',
        'Apa sinopsis film {film}?',
        'Apa isi sinopsis dari film {film}?',
        'Apa isi sinopsis film {film}?'
    ],
    q7: [
        'Apa judul film yang sedang tayang?',
        'Apa saja judul film yang sedang tayang?',
        'Apa nama film yang sedang tayang?',
        'Apa saja nama film yang sedang tayang?',
        'Film apa yang sedang tayang?',
        'Film apa saja yang sedang tayang?',
        'Apa judul film yang sedang tayang?',
        'Apa saja judul film yang sedang tayang?',
        'Apa judul film yang sedang tayang hari ini?',
        'Apa saja judul film yang sedang tayang hari ini?',
        'Apa nama film yang sedang tayang hari ini?',
        'Apa saja nama film yang sedang tayang hari ini?',
        'Film apa yang sedang tayang hari ini?',
        'Film apa saja yang sedang tayang hari ini?',
        'Apa judul film yang sedang tayang hari ini?',
        'Apa saja judul film yang sedang tayang hari ini?',
        'Apa judul film yang hari ini sedang tayang?',
        'Apa saja judul film yang hari ini sedang tayang?',
        'Apa nama film yang hari ini sedang tayang?',
        'Apa saja nama film yang hari ini sedang tayang?',
        'Film apa yang hari ini sedang tayang?',
        'Film apa saja yang hari ini sedang tayang?',
        'Apa judul film yang hari ini sedang tayang?',
        'Apa saja judul film yang hari ini sedang tayang?',
        'Hari ini film apa yang sedang tayang?',
        'Hari ini film apa saja yang sedang tayang?',
        'Apa judul film yang lagi tayang?',
        'Apa saja judul film yang lagi tayang?',
        'Apa nama film yang lagi tayang?',
        'Apa saja nama film yang lagi tayang?',
        'Film apa yang lagi tayang?',
        'Film apa saja yang lagi tayang?',
        'Apa judul film yang lagi tayang?',
        'Apa saja judul film yang lagi tayang?',
        'Apa judul film yang lagi tayang hari ini?',
        'Apa saja judul film yang lagi tayang hari ini?',
        'Apa nama film yang lagi tayang hari ini?',
        'Apa saja nama film yang lagi tayang hari ini?',
        'Film apa yang lagi tayang hari ini?',
        'Film apa saja yang lagi tayang hari ini?',
        'Apa judul film yang lagi tayang hari ini?',
        'Apa saja judul film yang lagi tayang hari ini?',
        'Apa judul film yang hari ini lagi tayang?',
        'Apa saja judul film yang hari ini lagi tayang?',
        'Apa nama film yang hari ini lagi tayang?',
        'Apa saja nama film yang hari ini lagi tayang?',
        'Film apa yang hari ini lagi tayang?',
        'Film apa saja yang hari ini lagi tayang?',
        'Apa judul film yang hari ini lagi tayang?',
        'Apa saja judul film yang hari ini lagi tayang?',
        'Hari ini film apa yang lagi tayang?',
        'Hari ini film apa saja yang lagi tayang?'
    ],
    q8: [
        'Apa judul film yang akan tayang?',
        'Apa saja judul film yang akan tayang?',
        'Apa nama film yang akan tayang?',
        'Apa saja nama film yang akan tayang?',
        'Film apa yang akan tayang?',
        'Film apa saja yang akan tayang?',
        'Apa judul film yang nanti akan tayang?',
        'Apa saja judul film yang nanti akan tayang?',
        'Apa judul film yang nanti akan tayang?',
        'Apa saja judul film yang nanti akan tayang?',
        'Apa nama film yang nanti akan tayang?',
        'Apa saja nama film yang nanti akan tayang?',
        'Film apa yang nanti akan tayang?',
        'Film apa saja yang nanti akan tayang?',
        'Apa judul film yang nanti akan tayang?',
        'Apa saja judul film yang nanti akan tayang?'
    ]
};
